meta:
  local: true # If true, this will use local files for datasets and pretrained models
local:
  cache_dir: /Users/adnansiddiquei/DocsLocal/AstroClip/astroclip/cache # Directory containing datasets and pretrained models
  output_dir: /Users/adnansiddiquei/DocsLocal/AstroClip/astroclip/out # Directory to save output files
hpc:
  cache_dir: /todo
  output_dir: /todo
