local:  # config for local machine
  cache_dir: /Users/adnansiddiquei/DocsLocal/AstroClip/astroclip/cache
  output_dir: /Users/adnansiddiquei/DocsLocal/AstroClip/astroclip/out
  num_workers: 5
  pretrained_spectrum_encoder: spender.desi-edr.encoder.pth  # filename of model in cache_dir
  pretrained_image_encoder: resnet50.ckpt
hpc:  # config for running on Cambridge HPC
  cache_dir: /home/as3438/rds/hpc-work/astroclip/cache
  output_dir: /home/as3438/rds/hpc-work/astroclip/out
  num_workers: 32
  pretrained_spectrum_encoder: spender.desi-edr.encoder.pth
  pretrained_image_encoder: resnet50.ckpt
